### ISSUE TITLE
[Bug] Clear list on `enter` key press

### ISSUE THREAD

**Issue by nurcahyopujo** [NurfitraPujo/todolist#1]
#### Description
when create new todo by press `enter`key on form input, page reload and created todo list cleared

#### Screenshots
![bug clear](https://user-images.githubusercontent.com/1446387/53215349-d1803700-3682-11e9-8210-d636b27ac892.gif)

#### To Reproduce
create some todo with click button, then create todo with `enter` key

#### Tasks
- add handler onform submit

@NurfitraPujo

**Comment by NurfitraPujo** [comment]
Fixed after adding `onsubmit="return false"` in form element
